version: '3.8'

services:
  microservicea:
    build:
      context: microservice-a
      dockerfile: Dockerfile-a
    container_name: microservicea
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - spring.profiles.active=docker

  microserviceb:
    build:
      context: microservice-b
      dockerfile: Dockerfile-b
    container_name: microserviceb
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      - spring.profiles.active=docker

  db:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_DB: demodb
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: